# Generated by Django 2.2.28 on 2025-03-27 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_age_difference',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
