# Generated by Django 2.2.28 on 2025-03-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0003_userprofile_max_age_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
