# Generated by Django 2.2.28 on 2025-03-28 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0007_auto_20250328_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_ranges',
            field=models.ManyToManyField(blank=True, to='user_page.AgeRange'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budgets',
            field=models.ManyToManyField(blank=True, to='user_page.Budget'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, default='No bio yet :(', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_needs',
            field=models.ManyToManyField(blank=True, to='user_page.DietaryNeed'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dining_vibes',
            field=models.ManyToManyField(blank=True, to='user_page.DiningVibe'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regional_cuisines',
            field=models.ManyToManyField(blank=True, to='user_page.Cuisine'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
